services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/data
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    ports:
      - "8001:8000"
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - chromadb_cache:/root/.cache/chroma/onnx_models
      - ./src:/app/src
    depends_on:
      - chromadb
    restart: always

  ui:
    build:
      context: .
      dockerfile: Dockerfile
      target: ui
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    depends_on:
      - api
    restart: always
    environment:
      - PYTHONPATH=/app

volumes:
  chroma_data:
  chromadb_cache: