services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/root/.cache/chroma/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot_app
    ports:
      - "5000:5000"
      - "8501:8501"
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
      - GROQ_API_KEY=${GROQ_API_KEY}
    depends_on:
      - chromadb
    volumes:
      - chromadb_cache:/root/.cache/chroma/onnx_models

volumes:
  chromadb_data:
  chromadb_cache:
